#!/usr/bin/env python3
"""Regenerate src/resources/style/_fonts.scss with base64-embedded woff2 fonts.

The fonts are embedded as data URIs (not linked as separate files) so there is
no font network request for a corporate VPN / secure web gateway to block —
those gateways commonly filter .otf/.ttf downloads (or all font MIME types),
which made the page fall back to system fonts.

Usage:
    pip install fonttools brotli      # one-time
    python3 scripts/embed-fonts.py    # run from repo root after changing a font

Add or edit a font by updating FACES below (source may be .ttf/.otf/.woff).
"""
import base64
import os

from fontTools.ttLib import TTFont

FONT_DIR = "src/resources/fonts"
OUT = "src/resources/style/_fonts.scss"

# (font-family, font-weight, source file relative to FONT_DIR)
FACES = [
    ("PPNeueBit", 400, "PPNeueBit-Regular.ttf"),
    ("PPNeueBit", 700, "PPNeueBit-Bold.otf"),
    ("CallingCode", 400, "CallingCode-Regular.otf"),
]


def to_woff2_bytes(src_path: str) -> bytes:
    """Load any font format and return its woff2-flavored bytes."""
    woff2_path = os.path.splitext(src_path)[0] + ".woff2"
    font = TTFont(src_path)
    font.flavor = "woff2"
    font.save(woff2_path)  # keep a copy on disk as the regeneration source
    with open(woff2_path, "rb") as f:
        return f.read()


def main() -> None:
    lines = [
        "// AUTO-GENERATED by scripts/embed-fonts.py — do not edit by hand.\n",
        "// Fonts are base64 data URIs so there is no separate font request for\n",
        "// a VPN / secure web gateway to block. Regenerate after changing a font:\n",
        "//     python3 scripts/embed-fonts.py\n\n",
    ]
    for family, weight, name in FACES:
        data = to_woff2_bytes(os.path.join(FONT_DIR, name))
        b64 = base64.b64encode(data).decode()
        lines += [
            "@font-face {\n",
            f"  font-family: '{family}';\n",
            f"  src: url('data:font/woff2;base64,{b64}') format('woff2');\n",
            f"  font-weight: {weight};\n",
            "  font-style: normal;\n",
            "  font-display: swap;\n",
            "}\n\n",
        ]
    with open(OUT, "w") as f:
        f.write("".join(lines))
    print(f"wrote {OUT} ({os.path.getsize(OUT)} bytes) with {len(FACES)} faces")


if __name__ == "__main__":
    main()
